# These are supported funding model platforms

github: #  e.g., [@pemasaran7, @klikshop01]
patreon: #  [Toko]
open_collective: #  @subOlshop
ko_fi: #  Ko-fi-Tika
tidelift: #  e.g., npm/package.github.com/TUTORIAL-HALAMAN
community_bridge: #  e.g.,TUTORIAL-HALAMAN
liberapay: # klik-organisasi
issuehunt: # fatidelfat@gmail.com
otechie: # @pemasaran7
custom: #  e.g., ['https://facebook.com/pemasaran7', 'https://facebook.com/klikshop01']
